# Generated by Django 5.0.3 on 2024-07-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('content', models.CharField(blank=True, max_length=1000, null=True)),
                ('comment', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='posts')),
                ('color', models.CharField(choices=[('빨강', '빨강(Red)'), ('주황', '주황(Orange)'), ('노랑', '노랑(Yellow)'), ('초록', '초록(Green)'), ('파랑', '파랑(Blue)'), ('보라', '보라(Purple)')], default='', max_length=2)),
                ('date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
