# Generated by Django 5.0.6 on 2024-07-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': '해당 이메일이 이미 존재합니다.'}, max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(error_messages={'unique': '해당 닉네임이 이미 존재합니다.'}, max_length=50, unique=True),
        ),
    ]
