# Generated by Django 5.0.6 on 2024-07-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_achievements', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userachievement',
            name='locked',
        ),
        migrations.AddField(
            model_name='userachievement',
            name='unlocked',
            field=models.BooleanField(default=False),
        ),
    ]
